# Generated by Django 2.2.6 on 2020-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='country_code',
            field=models.IntegerField(blank=True, default=234, null=True),
        ),
    ]
