# Generated by Django 2.2.6 on 2020-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20201007_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
