# Generated by Django 2.2.6 on 2020-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20201106_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
