# Generated by Django 4.0.5 on 2022-12-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20201121_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
