# Generated by Django 2.2.6 on 2020-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='availability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
