# Generated by Django 2.2.6 on 2020-11-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201020_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to='product/image'),
        ),
    ]
