# Generated by Django 2.2.6 on 2020-11-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201103_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(default='shoe', max_length=100),
            preserve_default=False,
        ),
    ]
