# Generated by Django 2.2.6 on 2020-11-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201111_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.TextField(),
        ),
    ]
