# Generated by Django 2.2.6 on 2020-11-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201111_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
