# Generated by Django 2.2.6 on 2020-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201121_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images_left',
            field=models.FileField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='images_right',
            field=models.FileField(blank=True, null=True, upload_to='product/images'),
        ),
    ]
