# Generated by Django 2.2.6 on 2020-11-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201121_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
