# Generated by Django 4.0.5 on 2023-02-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productvariant_productpriceranges_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='images_left',
        ),
        migrations.RemoveField(
            model_name='products',
            name='images_right',
        ),
    ]
