# Generated by Django 2.2.6 on 2020-10-07 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='salerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
