# Generated by Django 2.2.6 on 2020-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201007_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='collected_time',
            field=models.DateTimeField(blank=True, help_text='Date item was collected by delivery company', null=True),
        ),
    ]
