# Generated by Django 2.2.6 on 2020-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201009_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='package_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
