# Generated by Django 2.2.6 on 2020-10-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_salerecord_package_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='salerecord',
            name='returned',
        ),
    ]
