# Generated by Django 2.2.6 on 2020-10-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201009_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
    ]
