# Generated by Django 2.2.6 on 2020-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pack_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
