# Generated by Django 2.2.6 on 2020-10-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_salerecord_returned_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['-timestamp']},
        ),
    ]
