# Generated by Django 2.2.6 on 2020-12-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_salerecord_shiping_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
