# Generated by Django 2.2.6 on 2020-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201219_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='delivery_type',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
