# Generated by Django 4.1.4 on 2023-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_pack_id_alter_salerecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='price_per_one',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
