# Generated by Django 2.2.6 on 2020-10-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='savings_balance',
            new_name='available_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='ledger_balance',
            field=models.IntegerField(default=0),
        ),
    ]
