# Generated by Django 2.2.6 on 2020-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0002_auto_20201009_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
