# Generated by Django 2.2.6 on 2020-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0003_account_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='percent_commition',
            field=models.CharField(default=50, max_length=20),
        ),
    ]
