# Generated by Django 2.2.6 on 2020-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='achievements',
        ),
        migrations.AddField(
            model_name='company',
            name='areas_covered',
            field=models.CharField(default=1, help_text='Locations where your products can be availavle for delivery. Seperate each with semi colon (;)', max_length=260),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='monitor',
            field=models.CharField(default=1, help_text='Ojaa monitors and enhances your mode of operation', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(default=1, upload_to='company/images'),
            preserve_default=False,
        ),
    ]
