# Generated by Django 2.2.6 on 2020-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201114_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='areas_covered',
            field=models.CharField(help_text='Locations where your products can be available for delivery. Seperate each with semi colon (;)', max_length=260),
        ),
    ]
