# Generated by Django 2.2.6 on 2020-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201114_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='self_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
