# Generated by Django 2.2.6 on 2020-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_self_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_delivery_cost',
            field=models.IntegerField(default=900),
        ),
    ]
