# Generated by Django 2.2.6 on 2020-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_average_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shiping_msg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
