# Generated by Django 2.2.6 on 2020-11-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_shiping_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shiping_msg',
        ),
    ]
