# Generated by Django 4.0.5 on 2023-02-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_has_paid_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('R', 'Retail Store'), ('W', 'Wholesale Store'), ('M', 'Manufacturer')], default='M', max_length=1),
        ),
    ]
