# Generated by Django 4.1.4 on 2023-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='areas_covered',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('W', 'Wholesale Store'), ('M', 'Manufacturer')], default='M', max_length=1),
        ),
    ]
