# Generated by Django 2.2.6 on 2021-01-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card', models.IntegerField(default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('savings', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
