# Generated by Django 2.2.6 on 2020-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='in_cart', to='accounts.SaleRecord'),
        ),
    ]
