# Generated by Django 2.2.6 on 2020-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201019_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='advert_email_unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
