# Generated by Django 2.2.6 on 2020-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_advert_email_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_type',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
